id: PA4C33416
initial_creation_type: input
source_metadata:
  title: Shechen Rabjam Rinpoche Series
  language: en
  description: 'Texts by and about Jigme Chökyi Senge (''jigs med chos kyi seng+ge,
    b. 1966), the seventh Rabjam Rinpoche of Shechen Monastery:'
  volume:
    6ad953dcd7b641c7900a07f5a7a1dee6:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    48c870dfd4184aef84b4e97a495be495:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Long Life Prayers
    833f8fc480c547f1a19b743f7f286df1:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    b9a2fed82e134e16a9c5a4cb300bcc2e:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    2e5c0fd0b37e4aedbe465e1cc20b51c3:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Prayers
    af023f76872c4c1f8ee0be9051eb12f8:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    fdd18dc904be4238a19b13a6a226e8f5:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    4c993362afe84e9bb6502a4b2cc7edeb:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:35:58.831931'
last_modified_at: '2022-03-01T01:35:58.831937'
